config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  concern :voteable do
    post 'vote/:type', action: :vote, on: :member, as: :vote
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  devise_scope :user do
    get 'register' => 'registrations#new', as: :new_user_registration
    get 'profile' => 'registrations#edit', as: :edit_user_registration
  end

  devise_for :users, path: '', only: [:sessions]
  devise_for :users, skip: [:sessions],
             controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'},
             path_names: { sign_up: 'register', edit: 'profile'}

  resources :users, only: [:index, :show], concerns: :paginatable

  get 'tags/:tag(/page/:page)', to: 'questions#index', as: :tag

  resources :questions, concerns: [:paginatable, :voteable, :commentable] do
    resources :answers, only: [:create]
  end

  scope :api, defaults: { format: 'json' }, constraints: { format: 'json' }, as: :api  do
    resources :questions, only: [:index, :show]
  end
  get :api, to: redirect('api/questions')

  resources :answers, only: [:edit, :update, :destroy], concerns: [:voteable, :commentable]

  root  'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include VoteableModel
  include FormatText

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable

  acts_as_taggable

  is_impressionable counter_cache: true, unique: [:impressionable_type, :impressionable_id, :ip_address]

  default_scope -> { order('created_at DESC') }

  before_validation :format_text, on: [:create, :update]

  validates :user, presence: true
  validates :text, presence: true
  validates :title, presence: true
  validates :tag_list, presence: true

  validate :max_tag_size

  private
    def max_tag_size
      return if self.tag_list.empty?
      errors[:tag_list] << '5 tags maximum' if self.tag_list.count > 5
      errors[:tag_list] << 'can\'t contain tag with length < 20 letters ' if self.tag_list.collect(&:length).max >= 20
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voteable

  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :ip_address]

  respond_to :html
  respond_to :json, only: [:index, :show]

  def index
    @questions = Question.includes_votes.includes(:tags).page params[:page]
    @questions = @questions.tagged_with(params[:tag]) if params[:tag]

    respond_with(@questions)
  end

  def show
    respond_with(@question)
  end

  def new
    @question = Question.new
    respond_with(@question)
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    flash[:notice] = 'Question was successfully created.' if @question.save
    respond_with(@question)
  end

  def update
    flash[:notice] = 'Question was successfully updated.' if @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def check_user
      unless current_user.id == @question.user.id
        flash[:alert] = 'You must be the owner of this question.'
        redirect_to @question
      end
    end

    def question_params
      params.require(:question).permit(:title, :text, :user_id, :tag_list)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      h2 = "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      ul
        - @question.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: 'What\'s your programming question? Be specific.'
  .form-group
    = f.label :text
    = f.text_area :text, class: 'form-control', placeholder: 'Type detailed question description here.'
  .form-group
    = f.label :tag_list, 'Tags'
    = f.text_field :tag_list, class: 'form-control', placeholder: 'Type tags (separated by commas)'
  .form-group
    = f.submit 'Save', class: 'btn btn-lg btn-primary'

app/views/questions/edit.html.slim
h1.page-header
  | Editing question
  = link_to 'Cancel', @question, class: 'btn btn-lg btn-default'
== render 'form'

app/views/questions/index.html.slim
h1.page-header
  | Recent Questions
  span
    = link_to 'Ask Question', new_question_path, class: 'btn btn-lg btn-success'

#tag-cloud
  - tag_cloud Question.tag_counts, %w{t1 t2 t3 t4 t5} do |tag, css_class|
    = link_to tag.name, tag_path(tag.name), class: "label label-default #{css_class}"
br

.list-group
  - @questions.each do |question|
    .list-group-item.row
      = link_to question, class: 'question-counters col-md-3 col-sm-3 row text-center' do
        .col-md-4.col-sm-4.pull-left
          h3
            = question.plusminus_tally
          = 'vote'.pluralize(question.plusminus_tally.abs)
        .col-md-4.col-sm-4.pull-left
          h3
            = question.answers.size
          = 'answer'.pluralize(question.answers.size)
        .col-md-4.col-sm-4.pull-left
          h3
            = question.impressions_count
          = 'view'.pluralize(question.impressions_count)
      .col-md-6.col-sm-6
        h4
          = link_to question, class: 'inverse' do
            = question.title
        div
          - question.tags.each do |tag|
            = link_to tag, tag_path(tag.name), class: 'label label-default'
      .col-md-3.col-sm-3.text-right
        span[data-toggle="tooltip" data-placement="top" data-title="#{question.created_at}"]
          = "asked #{time_ago_in_words(question.created_at)} ago"
        br
        == render question.user
.text-center
  == paginate @questions

app/views/questions/new.html.slim
h1.page-header
  | New question
  = link_to 'Cancel', questions_path, class: 'btn btn-lg btn-default'
== render 'form'

app/views/questions/show.html.slim
h3.page-header
  .icon-container.pull-right
    - if @question.user == current_user
      .icon.icon-lg.icon-edit[data-toggle="tooltip" data-placement="top" data-title="Edit question"]
        = link_to edit_question_path(@question) do
          span.glyphicon.glyphicon-pencil
      .icon.icon-lg.icon-delete[data-toggle="tooltip" data-placement="top" data-title="Delete this question"]
        = link_to question_path(@question), method: :delete, data: { confirm: 'Are you sure?' } do
          span.glyphicon.glyphicon-remove
  = @question.title
.row
  .col-md-1.col-sm-1.text-center
    - voted_how = current_user.voted_how?(@question) if user_signed_in?
    .icon.icon-lg.icon-upvote[class="#{'active' if voted_how == true}"]
      = link_to vote_question_path(@question, type: 'up'), method: :post, remote: true do
        span.glyphicon.glyphicon-chevron-up
    h4[class="q#{@question.id}_votes"] = @question.plusminus
    .icon.icon-lg.icon-downvote[class="#{'active' if voted_how == false}"]
      = link_to vote_question_path(@question, type: 'down'), method: :post, remote: true do
        span.glyphicon.glyphicon-chevron-down
  .col-md-8.col-sm-8
    p
      == @question.text.html_safe
    p
      - @question.tag_list.each do |tag|
        = link_to tag, tag_path(tag), class: 'label label-default'
  .col-md-3.col-sm-3.pull-right.text-right
    span[data-toggle="tooltip" data-placement="top" data-title="#{@question.created_at}"]
      = "asked #{time_ago_in_words(@question.created_at)} ago"
    br
    == render @question.user

- if @question.comments.any?
  .row[id="q#{@question.id}-comments"]
    == render @question.comments
- if user_signed_in?
  - comments_form_id = "q#{@question.id}-comments-form"
  .row
    .col-md-8.col-md-offset-1.col-sm-8.col-sm-offset-1
      a.lighten.dotted[data={target: '#' + comments_form_id, toggle: 'collapse'} aria-expanded="true" aria-controls=comments_form_id]
        | add comment
      .collapse[id=comments_form_id]
        == render 'comments/form', commentable: @question

h4.page-header
  = pluralize(@question.answers.size, 'Answer')
#answers
  == render @question.answers.includes_votes.by_rating
#answer-form
  == render 'answers/form' if user_signed_in?