config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  concern :voteable do
    post 'vote/:type', action: :vote, on: :member, as: :vote
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  devise_scope :user do
    get 'register' => 'registrations#new', as: :new_user_registration
    get 'profile' => 'registrations#edit', as: :edit_user_registration
  end

  devise_for :users, path: '', only: [:sessions]
  devise_for :users, skip: [:sessions],
             controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'},
             path_names: { sign_up: 'register', edit: 'profile'}

  resources :users, only: [:index, :show], concerns: :paginatable

  get 'tags/:tag(/page/:page)', to: 'questions#index', as: :tag

  resources :questions, concerns: [:paginatable, :voteable, :commentable] do
    resources :answers, only: [:create]
  end

  scope :api, defaults: { format: 'json' }, constraints: { format: 'json' }, as: :api  do
    resources :questions, only: [:index, :show]
  end
  get :api, to: redirect('api/questions')

  resources :answers, only: [:edit, :update, :destroy], concerns: [:voteable, :commentable]

  root  'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include VoteableModel
  include FormatText

  belongs_to :question, counter_cache: true
  belongs_to :user
  has_many :comments, as: :commentable

  before_validation :format_text, on: [:create, :update]

  validates :user, presence: true
  validates :text, presence: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voteable

  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:create]
  before_action :set_answer, only: [:edit, :update, :destroy]

  respond_to :html
  respond_to :js, only: [:create, :destroy]

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    flash[:notice] = 'Successfully answered.' if @answer.save
    respond_with(@answer.question)
  end

  def update
    flash[:notice] = 'Answer was successfully updated.' if @answer.update(answer_params)
    respond_with(@answer.question)
  end

  def destroy
    @answer.destroy
    flash[:notice] = 'Answer was successfully deleted.' unless @answer.errors.any?
    respond_with(@answer.question)
  end

  private
    def set_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:text, :question_id, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer
  .row[id="a#{answer.id}"]
    .col-md-1.col-sm-1.text-center
      - voted_how = current_user.voted_how?(answer) if user_signed_in?
      .icon.icon-lg.icon-upvote[class="#{'active' if voted_how == true}"]
        = link_to vote_answer_path(answer, type: 'up'), method: :post, remote: true do
          span.glyphicon.glyphicon-chevron-up
      h4[class="a#{answer.id}_votes"]
        - if answer.respond_to?(:plusminus_tally)
          = answer.plusminus_tally
        - else
          = answer.plusminus
      .icon.icon-lg.icon-downvote[class="#{'active' if voted_how == false}"]
        = link_to vote_answer_path(answer, type: 'down'), method: :post, remote: true do
          span.glyphicon.glyphicon-chevron-down
    .col-md-8.col-sm-8
      - if answer.user == current_user
        .icon-container.pull-right
          .icon.icon-edit[data-toggle="tooltip" data-placement="top" data-title="Edit answer"]
            = link_to edit_answer_path(answer) do
              span.glyphicon.glyphicon-pencil
          .icon.icon-delete[data-toggle="tooltip" data-placement="top" data-title="Delete this answer"]
            = link_to answer_path(answer), method: :delete, remote: true, data: { confirm: 'Are you sure?' } do
              span.glyphicon.glyphicon-remove
      p
        == answer.text.html_safe
    .col-md-3.col-sm-3.pull-right.text-right
      span[data-toggle="tooltip" data-placement="top" data-title="#{answer.created_at}"]
        = "answered #{time_ago_in_words(answer.created_at)} ago"
      br
      == render answer.user

  - if answer.comments.any?
    .row[id="a#{answer.id}-comments"]
      == render answer.comments
  - if user_signed_in?
    - comments_form_id = "a#{answer.id}-comments-form"
    .row
      .col-md-8.col-md-offset-1.col-sm-8.col-sm-offset-1
        a.lighten.dotted[data={target: '#' + comments_form_id, toggle: 'collapse'} aria-expanded="true" aria-controls=comments_form_id]
          | add comment
        .collapse[id=comments_form_id]
          == render 'comments/form', commentable: answer

app/views/answers/_form.html.slim
- @answer ||= @question.answers.build if user_signed_in?
- remote = true unless controller_name == 'answers'
= form_for [@question, @answer], remote: remote do |f|
  - if @answer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      ul
        - @answer.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.text_area :text, class: 'form-control', placeholder: 'Your answer.'
  .form-group
    = f.submit 'Answer', class: 'btn btn-lg btn-success'

app/views/answers/create.js.erb
<% if @answer.errors.any? -%>
<%= render :partial => 'layouts/errors', locals: {errors: @answer.errors.full_messages} -%>
<% else -%>
$("<%= escape_javascript(render @answer) %>").appendTo("#answers");
$('#answer-form form')[0].reset();
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.any? -%>
<%= render :partial => 'layouts/errors', locals: {errors: @answer.errors.full_messages} -%>
<% else -%>
$("#a<%= @answer.id %>").remove();
<% end %>

app/views/answers/edit.html.slim
h1.page-header
  | Editing answer
  = link_to 'Cancel', @answer.question, class: 'btn btn-lg btn-default'
== render 'form'