config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  concern :voteable do
    post 'vote/:type', action: :vote, on: :member, as: :vote
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  devise_scope :user do
    get 'register' => 'registrations#new', as: :new_user_registration
    get 'profile' => 'registrations#edit', as: :edit_user_registration
  end

  devise_for :users, path: '', only: [:sessions]
  devise_for :users, skip: [:sessions],
             controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'},
             path_names: { sign_up: 'register', edit: 'profile'}

  resources :users, only: [:index, :show], concerns: :paginatable

  get 'tags/:tag(/page/:page)', to: 'questions#index', as: :tag

  resources :questions, concerns: [:paginatable, :voteable, :commentable] do
    resources :answers, only: [:create]
  end

  scope :api, defaults: { format: 'json' }, constraints: { format: 'json' }, as: :api  do
    resources :questions, only: [:index, :show]
  end
  get :api, to: redirect('api/questions')

  resources :answers, only: [:edit, :update, :destroy], concerns: [:voteable, :commentable]

  root  'questions#index'

end

app/views/layouts/_errors.html.slim
- if errors.any?
  .alert.alert-dismissible.alert-danger
    button.close[type="button" data-dismiss="alert"]
      span[aria-hidden="true"] ×
      span.sr-only Close
    - errors.each do |text|
      - if text.is_a?(String)
      = text
      br

app/views/layouts/_errors.js.erb
$("#messages").append("<%= escape_javascript(render :partial => 'layouts/errors.html', locals: {errors: errors}).html_safe %>");

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - alert_class = "alert-#{name.to_s == 'alert' ? 'danger' : 'info'}"
    .alert.alert-dismissible[class=alert_class role="alert"]
      button.close[type="button" data-dismiss="alert"]
        span[aria-hidden="true"] ×
        span.sr-only Close
      = msg

app/views/layouts/_navigation.html.slim
= navbar static: :top, inverse: true do
  = navbar_header do
    = link_to root_url, class: 'navbar-brand' do
      = image_tag 'logo.png'
      .glitch
        - 3.times do
          span
            | OutOf
            strong Memory
  = navbar_collapse do
    = navbar_group id: 'menu' do
      = navbar_item 'Questions', questions_path
      = navbar_item 'Users', users_path
    == render '/layouts/user_menu'

app/views/layouts/_user_menu.html.slim
= navbar_group id: 'user-menu', align: 'right' do
  - if user_signed_in?
    = navbar_item edit_user_registration_path, id: 'navbar-profile' do
      - if current_user.avatar.thumb.url.present?
        = image_tag current_user.avatar.thumb.url, class: 'img-rounded'
      = current_user.login
    = navbar_item 'Sign Out', destroy_user_session_path, {}, {:'data-method' => :delete}
  - else
    = navbar_item 'Register', new_user_registration_path, {}, {'data-no-turbolink' => true}
    = navbar_item 'Sign In', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title = content_for?(:title) ? yield(:title) : 'OutOfMemory'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'OutOfMemory'}"
    = favicon_link_tag '/favicon.png'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body[class=@body_class]
    header
      == render 'layouts/navigation'
    .container
      main[role="main"]
        #messages
          == render 'layouts/messages'
        #content
          == yield :content if content_for? :content
          == yield

app/views/layouts/application.js.erb
$("#messages").html("<%= escape_javascript(render :partial => 'layouts/messages').html_safe %>");
<%= yield %>

app/views/layouts/panel.html.slim
- content_for :content, flush: true do
  .row
    - @panel_col_class ||= 'col-sm-6 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4'
    div[class=@panel_col_class]
      .panel.panel-default
        .panel-heading
          == yield :panel_heading
        .panel-body
          == yield :panel_body
        .panel-footer
          == yield :panel_footer
== render  template: "layouts/application"